#pragma execution_character_set("utf-8")

#ifndef _QX_IM_EXPORT_H_
#define _QX_IM_EXPORT_H_

#ifdef _BUILDING_QX_IM
#define QX_IM_DLL_EXPORT QX_DLL_EXPORT_HELPER
#else // _BUILDING_QX_IM
#define QX_IM_DLL_EXPORT QX_DLL_IMPORT_HELPER
#endif // _BUILDING_QX_IM

#ifdef _BUILDING_QX_IM
#define QX_REGISTER_HPP_QX_IM     QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_QX_IM     QX_REGISTER_CPP_EXPORT_DLL
#else // _BUILDING_QX_IM
#define QX_REGISTER_HPP_QX_IM     QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_QX_IM     QX_REGISTER_CPP_IMPORT_DLL
#endif // _BUILDING_QX_IM

#endif // _QX_IM_EXPORT_H_
